const detailStyle=document.createElement("style");
detailStyle.textContent=`.char{font:inherit;color:inherit;text-align:left;cursor:pointer}.char:hover{outline:2px solid #4aa3ff}.charDetail{padding:16px}.detailGrid{display:grid;gap:12px}.detailCard{background:var(--p2);border:1px solid var(--line);border-radius:12px;padding:14px}.detailCard h3{margin:0 0 10px}.detailCard h3 small{color:var(--muted)}.detailCard p{line-height:1.65}.detailCard details{border-top:1px solid var(--line);padding:9px 0}.detailCard summary{cursor:pointer;color:#cfe7ff;font-weight:700}#charDialog{width:min(1000px,96vw);height:min(92vh,1000px);overflow-y:auto}`;
document.head.append(detailStyle);
const iconStyle=document.createElement("style");
iconStyle.textContent=`.detailCard h3{display:flex;align-items:center;gap:10px}.detailSkillIcon{width:52px;height:52px;border-radius:10px;border:1px solid var(--line);object-fit:cover}.weaponMark{width:52px;height:52px;border-radius:10px;display:grid;place-items:center;background:#5b491f;border:1px solid #ffd36b;font-size:28px}`;
document.head.append(iconStyle);
const weaponIconRule=document.createElement("style");
weaponIconRule.textContent=".weaponMark{display:none!important}";
document.head.append(weaponIconRule);
const sampleStyle=document.createElement("style");
sampleStyle.textContent=`.charHero{display:flex;gap:14px;align-items:center;margin-bottom:14px}.charHero img{width:76px;height:76px;border-radius:14px;border:2px solid #ffd36b;object-fit:cover}.charBadges{display:flex;gap:6px;flex-wrap:wrap}.charBadge{background:#ffffff14;border:1px solid var(--line);border-radius:999px;padding:4px 8px;font-size:12px}.charTabs{display:grid;grid-template-columns:repeat(4,1fr);margin-bottom:14px}.charTab{padding:12px 4px;border:1px solid var(--line);background:var(--p2);color:var(--muted)}.charTab.active{background:#2678b8;color:#fff;font-weight:800}.charPane{display:none}.charPane.active{display:block}.levelModes{display:flex;gap:8px;margin-bottom:10px}.levelMode{padding:7px 11px;border:1px solid var(--line);border-radius:8px;background:var(--p2);color:var(--muted)}.levelMode.active{background:#2678b8;color:#fff}.skillLevels details:not(:last-child){display:none}.skillLevels.showAll details{display:block}.basicStats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.basicStats div{background:var(--p2);border:1px solid var(--line);border-radius:10px;padding:10px}.basicStats small{display:block;color:var(--muted)}@media(max-width:650px){.charTabs{grid-template-columns:repeat(2,1fr)}.basicStats{grid-template-columns:repeat(2,1fr)}}`;
document.head.append(sampleStyle);
function detailSkill(s,type,icon){const effect=s.effect||s.levels.map(x=>x.description).join("\n");return `<article class="detailCard"><h3>${icon?`<img class="detailSkillIcon" src="${esc(icon)}" loading="lazy" alt="">`:""}<span>${esc(type)}：${esc(s.name)}${s.ct?` <small>CT ${s.ct}</small>`:""}</span></h3><div class="skillEffect"><p>${esc(effect).replace(/\n/g,"<br>")}</p></div><div class="skillLevels">${s.levels.slice(0,4).map((x,i)=>`<details ${i===s.levels.length-1?"open":""}><summary>Lv${x.skillLevel||i+1}</summary><p>${esc(x.description).replace(/\n/g,"<br>")}</p></details>`).join("")}</div></article>`}
function showCharacterV2(id,characterIcon){const c=S.master?.characters?.[id];if(!c)return;const st=c.stats||{},w=c.weapon,icons=c.skillIcons||[];$("ctitle").textContent=`${c.subName?`［${c.subName}］`:""}${c.name}`;$("cbody").innerHTML=`<div class="charHero">${characterIcon?`<img src="${esc(characterIcon)}" alt="">`:""}<div><h2>${c.subName?`［${esc(c.subName)}］`:""}${esc(c.name)}</h2><div class="charBadges"><span class="charBadge">${esc(c.element)}属性</span><span class="charBadge">${esc(c.job)}</span><span class="charBadge">基礎速度 ${fmt(st.speed)}</span><span class="charBadge">キャラLv240時点</span></div></div></div><nav class="charTabs"><button class="charTab active" data-pane="skill">スキル性能</button><button class="charTab" data-pane="basic">基本ステータス</button><button class="charTab" data-pane="weapon">専用スキル</button><button class="charTab" data-pane="arcana">アルカナ</button></nav><section class="charPane active" data-char-pane="skill"><div class="levelModes"><button class="levelMode active" data-all="0">効果のみ</button><button class="levelMode" data-all="1">全レベル詳細</button></div>${c.active.map((x,i)=>detailSkill(x,"アクティブ",icons[i])).join("")}${c.passive.map((x,i)=>detailSkill(x,"パッシブ",icons[i+2])).join("")}</section><section class="charPane" data-char-pane="basic"><div class="basicStats"><div><small>属性</small>${esc(c.element)}</div><div><small>武器種</small>${esc(c.job)}</div><div><small>スピード</small>${fmt(st.speed)}</div><div><small>腕力係数</small>${fmt(st.coefficients?.Muscle)}</div><div><small>技力係数</small>${fmt(st.coefficients?.Energy)}</div><div><small>魔力係数</small>${fmt(st.coefficients?.Intelligence)}</div><div><small>耐久力係数</small>${fmt(st.coefficients?.Health)}</div></div></section><section class="charPane" data-char-pane="weapon"><article class="detailCard"><h3>LRメタトロン：${esc(w?.name||"専用武器")}</h3>${w?.effects?.map((x,i)=>`<p><b>Lv${i+1}</b> ${esc(x)}</p>`).join("")||"<p>データなし</p>"}</article></section><section class="charPane" data-char-pane="arcana">${c.arcana.map(a=>`<article class="detailCard"><h3>${esc(a.name)}</h3></article>`).join("")||"<p>なし</p>"}</section>`;$("cbody").querySelectorAll(".charTab").forEach(b=>b.onclick=()=>{$("cbody").querySelectorAll(".charTab,.charPane").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("cbody").querySelector(`[data-char-pane="${b.dataset.pane}"]`).classList.add("active")});$("cbody").querySelectorAll(".levelMode").forEach(b=>b.onclick=()=>{const all=b.dataset.all==="1";$("cbody").querySelectorAll(".levelMode").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("cbody").querySelectorAll(".skillEffect").forEach(x=>x.hidden=all);$("cbody").querySelectorAll(".skillLevels").forEach(x=>x.classList.toggle("showAll",all))});$("charDialog").showModal();document.body.style.overflow="hidden"}

const arcanaStyle=document.createElement("style");
arcanaStyle.textContent=`.skillLevels{display:none}.skillLevels.showAll{display:block}.arcanaPair{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.arcanaPartner{display:grid;grid-template-columns:58px minmax(110px,1fr);align-items:center;gap:10px;background:#ffffff0b;border:1px solid var(--line);border-radius:12px;padding:9px}.arcanaPartner img{width:58px;height:58px;border-radius:10px;border:1px solid #ffd36b;object-fit:cover}.arcanaPartner small{display:block;color:var(--muted)}.arcanaEffects{margin-top:10px;padding:10px 12px;border-radius:10px;background:#17446855}.arcanaEffects p{margin:4px 0}`;
document.head.append(arcanaStyle);
const arcanaSourceStyle=document.createElement("style");
arcanaSourceStyle.textContent=`.arcanaSource{display:inline-block;margin-bottom:8px;color:var(--blue,#8dc9ff);font-size:11px;font-weight:800}.charPane h4{margin:13px 0 7px}.arcanaPlus{font-size:20px;font-weight:900;color:var(--gold,#ffd36b)}`;
document.head.append(arcanaSourceStyle);
const battleNames={1:"HP",2:"攻撃力",3:"物理防御力",4:"魔法防御力",5:"命中",6:"回避",7:"クリティカル",8:"クリティカル耐性",9:"クリティカルダメージ強化",10:"物理クリティカルダメージ緩和",11:"魔法クリティカルダメージ緩和",12:"防御貫通",13:"防御力",14:"ダメージ強化",15:"弱体効果命中",16:"弱体効果耐性",17:"カウンタ",18:"HP吸収",19:"スピード"};
const baseNames={1:"腕力",2:"技力",3:"魔力",4:"耐久力"};
function arcanaEffectText(x,names){const name=names[x.ParameterType]||`能力${x.ParameterType}`;if(x.ChangeParameterType===3)return `${name}：キャラLv×${fmt(x.Value)}`;if(x.ChangeParameterType===2)return `${name}：+${fmt(x.Value/100)}%`;return `${name}：+${fmt(x.Value)}`}
function rankingIconForId(id){return S.iconBase?`${S.iconBase}CHR_${String(id).padStart(6,"0")}_LR5_0.webp`:""}
function enhanceArcana(id){const c=S.master?.characters?.[id],pane=$("cbody").querySelector('[data-char-pane="arcana"]');if(!c||!pane)return;pane.innerHTML=c.arcana?.map(a=>{const members=a.members||[];const pair=members.map((pid,i)=>{const p=S.master.characters?.[pid]||{},icon=rankingIconForId(pid),fallbackName=a.memberNames?.[i]||`キャラID ${pid}`;return `${i?'<span class="arcanaPlus">＋</span>':''}<div class="arcanaPartner">${icon?`<img src="${esc(icon)}" loading="lazy" alt="">`:""}<div><small>${String(pid)===String(id)?"選択中":"セット相手"}</small><b>${p.subName?`［${esc(p.subName)}］`:""}${esc(p.name||fallbackName)}</b></div></div>`}).join("");const effects=a.effects||[];return `<article class="detailCard"><div class="arcanaSource">ichigo Games取得データ</div><h3>${esc(a.name)}</h3><h4>セットキャラクター</h4><div class="arcanaPair">${pair||"<span>セットキャラデータなし</span>"}</div><h4>アルカナ効果</h4><div class="arcanaEffects">${effects.map(x=>`<p>${esc(x)}</p>`).join("")||"<p>効果データなし</p>"}</div></article>`}).join("")||"<p>アルカナなし</p>"}
document.addEventListener("click",event=>{
  const button=event.target.closest("[data-char-id]");
  if(!button)return;
  event.stopPropagation();
  showCharacterV2(button.dataset.charId,button.querySelector("img")?.src||"");
  enhanceArcana(button.dataset.charId);
});
$("cclose").onclick=()=>{$("charDialog").close();document.body.style.overflow=""};
loadMaster();
