const WORLDS=[1177,1178,1179,1180],S={g:[],p:[],iconBase:""},$=id=>document.getElementById(id),fmt=n=>Number(n||0).toLocaleString("ja-JP"),oku=n=>(Number(n||0)/1e8).toFixed(2)+"億",esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c])),classOf=r=>r<=16?["Grandmaster","gm"]:r<=32?["Expert","ex"]:["Elite","el"];
const isExtension=location.protocol==="chrome-extension:";
S.master={};
function normalize(data){S.g=[];S.p=[];for(const id of WORLDS){const g=data[`guild_${id}`],p=data[`player_${id}`],w=id-1000;if(g?.data?.GuildData)S.g.push(...g.data.GuildData.map(x=>({w,n:x.GuildName,b:+x.GuildBattlePower||0,m:+x.GuildMemberCount||0})));if(p?.data?.PlayerData)S.p.push(...p.data.PlayerData.map(x=>({w,n:x.PlayerName,g:x.GuildName||"未所属",b:+x.BattlePower||0,deck:Array.isArray(x.DeckCharacterInfoList)?x.DeckCharacterInfoList:[]})))}S.g.sort((a,b)=>b.b-a.b);S.p.sort((a,b)=>b.b-a.b)}
function iconUrl(c){if(!S.iconBase||!c?.CharacterId)return"";return `${S.iconBase}CHR_${String(c.CharacterId).padStart(6,"0")}_${encodeURIComponent(c.RarityName||"N")}_0.webp`}
function deckHtml(deck){return `<div class="deck">${(deck||[]).map(c=>{const url=iconUrl(c),id=esc(c.CharacterId);return `<button class="char" data-char-id="${id}" type="button">${url?`<img class="charImg" src="${esc(url)}" loading="lazy" alt="キャラ${id}">`:""}<span class="charFallback" style="display:${url?"none":"block"}">ID ${id}</span><span class="lv">Lv${esc(c.Level)}</span><span class="rarity">${esc(c.RarityName||"")}</span></button>`}).join("")}</div>`}
function bindImageFallbacks(root=document){root.querySelectorAll("img.charImg:not([data-bound])").forEach(img=>{img.dataset.bound="1";img.addEventListener("error",()=>{img.style.display="none";if(img.nextElementSibling)img.nextElementSibling.style.display="block"})})}
function renderGuild(){const q=$("gq").value.trim().toLowerCase();let ix=q?S.g.findIndex(x=>x.n.toLowerCase()===q):-1;if(ix<0&&q)ix=S.g.findIndex(x=>x.n.toLowerCase().includes(q));$("gw").textContent=[...new Set(S.g.map(x=>"W"+x.w))].join(" / ")||"-";$("gc").textContent=fmt(S.g.length);$("grank").textContent=ix>=0?`${ix+1}位`:"-";$("g16").textContent=S.g[15]?oku(S.g[15].b):"-";$("gb").innerHTML=S.g.slice(0,+$("glim").value).map((x,i)=>{const[c,k]=classOf(i+1);return `<tr data-guild="${encodeURIComponent(x.n)}" data-world="${x.w}" class="${i===ix?"target":""}"><td>${i+1}</td><td>W${x.w}</td><td>${esc(x.n)}</td><td class="num">${fmt(x.b)}</td><td class="num">${oku(x.b)}</td><td class="num">${x.m}</td><td class="${k}">${c}</td></tr>`}).join("");document.querySelectorAll("#gb tr").forEach(tr=>tr.onclick=()=>showGuild(decodeURIComponent(tr.dataset.guild),+tr.dataset.world))}
function renderPlayer(){let a=S.p;const w=$("pw").value,q=$("pq").value.trim().toLowerCase();if(w!=="all")a=a.filter(x=>x.w===+w);if(q)a=a.filter(x=>x.n.toLowerCase().includes(q)||x.g.toLowerCase().includes(q));$("pc").textContent=fmt(S.p.length);$("ptop").textContent=a[0]?oku(a[0].b):"-";$("ph").textContent=fmt(a.length);$("pscope").textContent=w==="all"?"4鯖統合":"W"+w;$("pb").innerHTML=a.slice(0,+$("plim").value).map((x,i)=>`<tr><td>${i+1}</td><td>W${x.w}</td><td>${esc(x.n)}</td><td>${esc(x.g)}</td><td class="num">${fmt(x.b)}<br><small>${oku(x.b)}</small></td><td>${deckHtml(x.deck)}</td></tr>`).join("");bindImageFallbacks($("pb"))}
function showGuild(name,w){const a=S.p.filter(x=>x.w===w&&x.g===name).sort((a,b)=>b.b-a.b).slice(0,10);$("dtitle").textContent=`W${w} ${name} TOP10`;$("db").innerHTML=a.map((x,i)=>`<section class="member"><div class="memberRank">${i+1}</div><div><div class="memberName">${esc(x.n)}</div><div class="memberGuild">${esc(x.g)}</div><div class="memberPower">戦闘力 ${fmt(x.b)}（${oku(x.b)}）</div></div>${deckHtml(x.deck)}</section>`).join("");bindImageFallbacks($("db"));$("dialog").showModal();document.body.style.overflow="hidden"}
function skillCard(s,type,icon){return `<article class="detailCard"><h3>${icon?`<img class="detailSkillIcon" src="${esc(icon)}" loading="lazy" alt="">`:""}<span>${esc(type)}：${esc(s.name)}${s.ct?` <small>CT ${s.ct}</small>`:""}</span></h3>${s.levels.map((x,i)=>`<details ${i===s.levels.length-1?"open":""}><summary>Lv${i+1}${x.level?`（解放Lv${x.level}）`:""}</summary><p>${esc(x.description)}</p></details>`).join("")}</article>`}
function showCharacter(id){const c=S.master?.characters?.[id];if(!c)return;$("ctitle").textContent=`${c.subName?`［${c.subName}］`:""}${c.name}`;const st=c.stats||{},w=c.weapon,icons=c.skillIcons||[];$("cbody").innerHTML=`<section class="detailGrid"><article class="detailCard"><h3>基本ステータス</h3><p>属性：${esc(c.element)}／武器種：${esc(c.job)}／スピード：${fmt(st.speed)}</p><p>腕力 ${fmt(st.coefficients?.Muscle)}・技力 ${fmt(st.coefficients?.Energy)}・魔力 ${fmt(st.coefficients?.Intelligence)}・耐久力 ${fmt(st.coefficients?.Health)}</p></article>${c.active.map((x,i)=>skillCard(x,"アクティブ",icons[i])).join("")}${c.passive.map((x,i)=>skillCard(x,"パッシブ",icons[i+2])).join("")}<article class="detailCard"><h3><span class="weaponMark">⚔</span> 専用武器（LRメタトロン）${w?`：${esc(w.name)}`:""}</h3>${w?.effects?.map((x,i)=>`<p><b>Lv${i+1}</b> ${esc(x)}</p>`).join("")||"<p>データなし</p>"}</article><article class="detailCard"><h3>アルカナ</h3>${c.arcana.map(a=>`<p><b>${esc(a.name)}</b></p>`).join("")||"<p>なし</p>"}</article></section>`;$("charDialog").showModal();document.body.style.overflow="hidden"}
async function loadMaster(){try{S.master=await fetch(isExtension?chrome.runtime.getURL("character-master.json"):`./data/character-master.json?t=${Date.now()}`).then(r=>r.json())}catch{S.master={}}}
async function load(){let data={},updated="";if(isExtension){const x=await chrome.storage.local.get(["rankingData","rankingUpdatedAt","rankingIconBase"]);data=x.rankingData||{};updated=x.rankingUpdatedAt||"";S.iconBase=x.rankingIconBase||""}else{const results=await Promise.all(WORLDS.flatMap(id=>["guild","player"].map(async kind=>{try{return [`${kind}_${id}`,await fetch(`./data/${kind}_${id}.json?t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json())]}catch{return null}})));for(const item of results)if(item)data[item[0]]=item[1];try{const st=await fetch(`./data/status.json?t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json());updated=st.updated_at_utc||""}catch{}try{const ic=await fetch(`./data/icon-config.json?t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json());S.iconBase=ic.base_url||""}catch{}}normalize(data);$("updated").textContent=updated?`最終取得: ${new Date(updated).toLocaleString("ja-JP")} / ${S.g.length}ギルド・${S.p.length}人`:"まだデータがありません。";renderGuild();renderPlayer()}
$("tg").onclick=()=>{$("guildSection").hidden=false;$("playerSection").hidden=true;$("tg").classList.add("active");$("tp").classList.remove("active")};$("tp").onclick=()=>{$("guildSection").hidden=true;$("playerSection").hidden=false;$("tp").classList.add("active");$("tg").classList.remove("active")};$("gq").oninput=renderGuild;$("glim").onchange=renderGuild;$("pw").onchange=renderPlayer;$("pq").oninput=renderPlayer;$("plim").onchange=renderPlayer;$("close").onclick=()=>{$("dialog").close();document.body.style.overflow=""};$("refresh").textContent=isExtension?"今すぐ全員分を更新":"最新データを再読込";$("refresh").onclick=()=>isExtension?chrome.runtime.sendMessage({type:"start"}):location.reload();if(isExtension)chrome.storage.onChanged.addListener(changes=>{if(changes.rankingData||changes.rankingUpdatedAt||changes.rankingIconBase)load()});else if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});load();
