const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const isExt=typeof chrome!=="undefined"&&chrome.runtime?.id;let API="",ICON="https://tamamo.dev/assets/CharacterIcon/",master={};
const rarity=["SR","SR+","SSR","SSR+","UR","UR+","LR","LR1","LR2","LR3","LR4","LR5","LR6","LR7","LR8","LR9","LR10"];
const icon=(id,r)=>`${ICON}CHR_${String(id).padStart(6,"0")}_${encodeURIComponent(r||"LR")}_0.webp`;
function charCard(c){return `<div class="char"><div class="portrait"><img src="${esc(icon(c.id,c.rarity))}" data-fallback="${esc(icon(c.id,"LR5"))}" alt=""></div><span class="lv">Lv${esc(c.level)}</span><span class="rarity">${esc(c.rarity)}</span><div class="stats">貫通 Lv${esc(c.penLevel)}×${esc(c.penCount)}<br>速度 Lv${esc(c.speedLevel)}×${esc(c.speedCount)}<br><span class="weapon">専用 ${esc(c.weapon)}</span><br>防具 ${esc(c.armor)}</div></div>`}
function render(rows){const groups=Map.groupBy?Map.groupBy(rows,x=>x.playerName):rows.reduce((m,x)=>(m.set(x.playerName,[...(m.get(x.playerName)||[]),x]),m),new Map());$("#players").innerHTML=[...groups].sort((a,b)=>a[0].localeCompare(b[0],"ja")).map(([name,list])=>`<section class="player"><div class="playerHead"><h2>${esc(name)}</h2><span>登録編成 ${list.length} / 15</span></div><div class="formations">${list.sort((a,b)=>a.formationNo-b.formationNo).map(x=>`<article class="formation"><h3>${x.formationNo}. ${esc(x.formationName)}</h3><div class="deck">${x.characters.map(charCard).join("")}</div></article>`).join("")}</div></section>`).join("")||"<p>まだ登録された編成はありません。</p>";document.querySelectorAll("img[data-fallback]").forEach(i=>i.onerror=()=>{if(i.src!==i.dataset.fallback)i.src=i.dataset.fallback})}
async function load(){try{if(isExt){const x=await chrome.storage.local.get(["formationsApiUrl","rankingIconBase"]);API=x.formationsApiUrl||"";ICON=x.rankingIconBase||ICON}else{const cfg=await fetch("./data/formations-config.json?t="+Date.now(),{cache:"no-store"}).then(r=>r.json());API=cfg.api_url||"";const ic=await fetch("./data/icon-config.json?t="+Date.now()).then(r=>r.json()).catch(()=>({}));ICON=ic.base_url||ICON}master=await fetch(isExt?chrome.runtime.getURL("character-master.json"):"./data/character-master.json").then(r=>r.json());if(!API){$("#status").textContent="編成登録機能は初期設定中です。";render([]);return}const out=await fetch(API+"?action=list&t="+Date.now(),{cache:"no-store"}).then(r=>r.json());if(!out.ok)throw Error(out.error||"読込失敗");$("#status").textContent=`${out.rows.length}編成を表示中`;render(out.rows)}catch(e){$("#status").textContent="読込エラー: "+e.message}}
function fields(){const opts=Object.values(master.characters||{}).sort((a,b)=>a.name.localeCompare(b.name,"ja")).map(c=>`<option value="${c.id}">${esc(c.subName?`［${c.subName}］${c.name}`:c.name)}</option>`).join("");$("#charFields").innerHTML=Array.from({length:5},(_,i)=>`<section class="editChar"><h3>キャラ${i+1}</h3><label>キャラ<select name="c${i}id" required><option value="">選択</option>${opts}</select></label><div class="pair"><label>レベル<input name="c${i}level" type="number" min="1" max="9999" required></label><label>レアリティ<select name="c${i}rarity">${rarity.map(r=>`<option>${r}</option>`).join("")}</select></label></div><label>貫通ルーン</label><div class="pair"><input name="c${i}penLevel" type="number" min="0" max="15" placeholder="Lv"><input name="c${i}penCount" type="number" min="0" max="3" placeholder="個数"></div><label>スピードルーン</label><div class="pair"><input name="c${i}speedLevel" type="number" min="0" max="15" placeholder="Lv"><input name="c${i}speedCount" type="number" min="0" max="3" placeholder="個数"></div><label>専用武器<select name="c${i}weapon"><option>黒</option><option>赤</option><option>紫</option></select></label><label>防具<select name="c${i}armor"><option>有</option><option>無</option></select></label></section>`).join("")}
function payload(form){const f=new FormData(form),characters=Array.from({length:5},(_,i)=>({id:+f.get(`c${i}id`),level:+f.get(`c${i}level`),rarity:f.get(`c${i}rarity`),penLevel:+f.get(`c${i}penLevel`)||0,penCount:+f.get(`c${i}penCount`)||0,speedLevel:+f.get(`c${i}speedLevel`)||0,speedCount:+f.get(`c${i}speedCount`)||0,weapon:f.get(`c${i}weapon`),armor:f.get(`c${i}armor`)}));return{action:"save",playerName:f.get("playerName").trim(),formationNo:+f.get("formationNo"),formationName:f.get("formationName").trim(),guildPassword:f.get("guildPassword"),editPassword:f.get("editPassword"),characters}}
$("#openForm").onclick=()=>{if(!API)return alert("管理者による初期設定が必要です。");fields();$("#formDialog").showModal();document.body.style.overflow="hidden"};$("#closeForm").onclick=()=>{$("#formDialog").close();document.body.style.overflow=""};$("#formationForm").formationNo.innerHTML=Array.from({length:15},(_,i)=>`<option>${i+1}</option>`).join("");$("#formationForm").onsubmit=async e=>{e.preventDefault();$("#formMessage").textContent="保存中…";try{const r=await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload(e.currentTarget))}).then(x=>x.json());if(!r.ok)throw Error(r.error||"保存失敗");$("#formMessage").textContent="保存しました。";await load()}catch(x){$("#formMessage").textContent=x.message}};load();
