const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const isExt=typeof chrome!=="undefined"&&chrome.runtime?.id;let API="",ICON="https://tamamo.dev/assets/CharacterIcon/",master={},rowsCache=[];
const rarity=["SR","SR+","SSR","SSR+","UR","UR+","LR","LR1","LR2","LR3","LR4","LR5","LR6","LR7","LR8","LR9","LR10"];
const icon=(id,r)=>`${ICON}CHR_${String(id).padStart(6,"0")}_${encodeURIComponent(r||"LR")}_0.webp`;
function runeText(items,oldLevel,oldCount){const list=(Array.isArray(items)?items:[{level:oldLevel,count:oldCount}]).filter(x=>+x.level>0&&+x.count>0);return list.length?list.map(x=>`Lv${esc(x.level)}×${esc(x.count)}`).join(" / "):"なし"}
function charCard(c){const portrait=c.id?`<img src="${esc(icon(c.id,c.rarity))}" data-fallback="${esc(icon(c.id,"LR5"))}" alt="">`:`<span class="manualName">キャラ未設定</span>`;return `<div class="char"><div class="portrait">${portrait}</div><span class="rarity">${esc(c.rarity)}</span><div class="stats">貫通 ${runeText(c.penetration,c.penLevel,c.penCount)}<br>速度 ${runeText(c.speed,c.speedLevel,c.speedCount)}<br><span class="weapon">専用 ${esc(c.weapon||"無し")}</span><br>防具 ${esc(c.armor)}</div></div>`}
function render(rows){rowsCache=rows;const groups=Map.groupBy?Map.groupBy(rows,x=>x.playerName):rows.reduce((m,x)=>(m.set(x.playerName,[...(m.get(x.playerName)||[]),x]),m),new Map());$("#players").innerHTML=[...groups].sort((a,b)=>a[0].localeCompare(b[0],"ja")).map(([name,list],i)=>`<section class="player"><button class="playerToggle" type="button" aria-expanded="false" aria-controls="player-formations-${i}"><span>${esc(name)}</span><small>登録編成 ${list.length} / 15</small></button><div class="playerDetails" id="player-formations-${i}" hidden><div class="playerMeta"><button class="renamePlayer" data-player="${esc(name)}" type="button">プレイヤー名変更</button><button class="deletePlayer" data-player="${esc(name)}" type="button">登録者削除</button><div class="playerLevel">共通レベル Lv${esc(list[0]?.characters?.[0]?.level||"-")}</div></div><div class="formations">${list.sort((a,b)=>a.formationNo-b.formationNo).map(x=>`<article class="formation"><div class="formationHead"><h3>${x.formationNo}. ${esc(x.formationName)}</h3><div class="formationActions"><button class="editFormation" data-id="${esc(x.id)}" type="button">修正</button><button class="resetFormation" data-id="${esc(x.id)}" type="button">初期化</button></div></div><div class="deck">${x.characters.map(charCard).join("")}</div><div class="formationExtra"><div class="formationReliability">編成信頼度 <span>${"★".repeat(Math.max(0,Math.min(5,+x.reliability||0)))}${"☆".repeat(5-Math.max(0,Math.min(5,+x.reliability||0)))}</span></div><div class="formationComment">${x.comment?esc(x.comment):"コメントなし"}</div></div></article>`).join("")}</div><button class="closePlayerDetails" type="button">このプレイヤーの編成を閉じる</button></div></section>`).join("")||"<p>まだ登録された編成はありません。</p>";document.querySelectorAll("img[data-fallback]").forEach(i=>i.onerror=()=>{if(i.src!==i.dataset.fallback)i.src=i.dataset.fallback});document.querySelectorAll(".playerToggle").forEach(b=>b.onclick=()=>{const d=document.getElementById(b.getAttribute("aria-controls")),open=b.getAttribute("aria-expanded")==="true";b.setAttribute("aria-expanded",String(!open));d.hidden=open});document.querySelectorAll(".closePlayerDetails").forEach(b=>b.onclick=()=>{const d=b.closest(".playerDetails"),toggle=document.querySelector(`[aria-controls="${d.id}"]`);d.hidden=true;toggle.setAttribute("aria-expanded","false");requestAnimationFrame(()=>toggle.scrollIntoView({block:"start",behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"}))});document.querySelectorAll(".renamePlayer").forEach(b=>b.onclick=()=>openRename(b.dataset.player));document.querySelectorAll(".deletePlayer").forEach(b=>b.onclick=()=>openDeletePlayer(b.dataset.player));document.querySelectorAll(".editFormation").forEach(b=>b.onclick=()=>openEditor(rowsCache.find(x=>String(x.id)===b.dataset.id)));document.querySelectorAll(".resetFormation").forEach(b=>b.onclick=()=>openReset(rowsCache.find(x=>String(x.id)===b.dataset.id)))}
async function load(){try{if(isExt){const x=await chrome.storage.local.get(["formationsApiUrl","rankingIconBase"]);API=x.formationsApiUrl||"";ICON=x.rankingIconBase||ICON}else{const cfg=await fetch("./data/formations-config.json?t="+Date.now(),{cache:"no-store"}).then(r=>r.json());API=cfg.api_url||"";const ic=await fetch("./data/icon-config.json?t="+Date.now()).then(r=>r.json()).catch(()=>({}));ICON=ic.base_url||ICON}master=await fetch(isExt?chrome.runtime.getURL("character-master.json"):"./data/character-master.json").then(r=>r.json());if(!API){$("#status").textContent="編成登録機能は初期設定中です。";render([]);return}const out=await fetch(API+"?action=list&t="+Date.now(),{cache:"no-store"}).then(r=>r.json());if(!out.ok)throw Error(out.error||"読込失敗");$("#status").textContent=`${out.rows.length}編成を表示中`;render(out.rows)}catch(e){$("#status").textContent="読込エラー: "+e.message}}
const runeLevels=Array.from({length:16},(_,i)=>`<option value="${i}">${i?`Lv${i}`:"無し"}</option>`).join(""),runeCounts=Array.from({length:4},(_,i)=>`<option value="${i}">${i?`${i}個`:"無し"}</option>`).join("");
function runeFields(i,type){return Array.from({length:3},(_,j)=>`<div class="pair"><select aria-label="ルーン${j+1}レベル" name="c${i}${type}Level${j}">${runeLevels}</select><select aria-label="ルーン${j+1}個数" name="c${i}${type}Count${j}">${runeCounts}</select></div>`).join("")}
function fields(){const opts=Object.values(master.characters||{}).sort((a,b)=>a.name.localeCompare(b.name,"ja")).map(c=>`<option value="${c.id}">${esc(c.subName?`［${c.subName}］${c.name}`:c.name)}</option>`).join("");$("#charFields").innerHTML=Array.from({length:5},(_,i)=>`<section class="editChar"><h3>キャラ${i+1}</h3><label>キャラ<select name="c${i}id"><option value="">選択</option>${opts}</select></label><label>レアリティ<select name="c${i}rarity">${rarity.map(r=>`<option>${r}</option>`).join("")}</select></label><label>貫通ルーン（3枠）</label><div class="runeRows">${runeFields(i,"pen")}</div><label>スピードルーン（3枠）</label><div class="runeRows">${runeFields(i,"speed")}</div><label>専用武器<select name="c${i}weapon"><option>黒</option><option>赤</option><option>紫</option><option>無し</option></select></label><label>防具<select name="c${i}armor"><option>２ミカ</option><option>４ミカ</option><option>２メタ</option><option>４メタ</option><option>６メタ</option><option>その他</option><option>無し</option></select></label></section>`).join("")}
let formationDrafts={},currentFormationNo=1;
const sharedNames=new Set(["playerName","commonLevel","guildPassword","editPassword","formationNo"]);
function captureDraft(form){const data={};for(const element of form.elements){if(element.name&&!sharedNames.has(element.name))data[element.name]=element.value}return data}
function applyDraft(form,draft){for(const [name,value] of Object.entries(draft||{})){if(form.elements[name])form.elements[name].value=value}}
function draftHasContent(draft){return Boolean(String(draft?.formationName||"").trim()||Array.from({length:5},(_,i)=>draft?.[`c${i}id`]).some(Boolean))}
function rowToDraft(row,base){const draft={...base,formationName:row.formationName||"",reliability:String(row.reliability||3),formationComment:row.comment||""};(row.characters||[]).slice(0,5).forEach((c,i)=>{draft[`c${i}id`]=String(c.id||"");draft[`c${i}rarity`]=c.rarity||"SR";oldRunes(c,"penetration").slice(0,3).forEach((x,j)=>{draft[`c${i}penLevel${j}`]=String(x.level||0);draft[`c${i}penCount${j}`]=String(x.count||0)});oldRunes(c,"speed").slice(0,3).forEach((x,j)=>{draft[`c${i}speedLevel${j}`]=String(x.level||0);draft[`c${i}speedCount${j}`]=String(x.count||0)});draft[`c${i}weapon`]=c.weapon||"無し";draft[`c${i}armor`]=c.armor==="有"?"その他":c.armor==="無"?"無し":c.armor||"無し"});return draft}
function drawFormationTabs(){const form=$("#formationForm");$("#formationTabs").innerHTML=Array.from({length:15},(_,i)=>{const no=i+1,filled=draftHasContent(formationDrafts[no]);return `<button type="button" class="formationTab${no===currentFormationNo?" active":""}${filled?" filled":""}" data-no="${no}">${no}</button>`}).join("");document.querySelectorAll(".formationTab").forEach(button=>button.onclick=()=>switchFormation(+button.dataset.no));$("#currentFormationLabel").textContent=`編成${currentFormationNo}`;$("#currentFormationState").textContent=draftHasContent(formationDrafts[currentFormationNo])?"登録内容あり":"未入力";form.formationNo.value=String(currentFormationNo)}
function switchFormation(no){const form=$("#formationForm");formationDrafts[currentFormationNo]=captureDraft(form);currentFormationNo=no;fields();applyDraft(form,formationDrafts[no]);drawFormationTabs();$("#formMessage").textContent=""}
function formationPayload(form,no,draft){const all=Object.values(master.characters||{}),commonLevel=+form.commonLevel.value,name=String(draft.formationName||"").trim();if(!name)throw Error(`編成${no}の編成名・用途を入力してください。`);const characters=Array.from({length:5},(_,i)=>{const selected=all.find(c=>+c.id===+draft[`c${i}id`]);if(!selected)throw Error(`編成${no}のキャラ${i+1}を選択してください。`);const runes=type=>Array.from({length:3},(_,j)=>{const level=+draft[`c${i}${type}Level${j}`]||0,count=+draft[`c${i}${type}Count${j}`]||0;if(Boolean(level)!==Boolean(count))throw Error(`編成${no}・キャラ${i+1}のルーンLvと個数を両方選択してください。`);return{level,count}});return{id:selected.id,name:selected.subName?`［${selected.subName}］${selected.name}`:selected.name,level:commonLevel,rarity:draft[`c${i}rarity`],penetration:runes("pen"),speed:runes("speed"),weapon:draft[`c${i}weapon`],armor:draft[`c${i}armor`]}});return{formationNo:no,formationName:name,reliability:+draft.reliability,comment:String(draft.formationComment||"").trim(),characters}}
function oldRunes(c,type){if(Array.isArray(c[type]))return c[type];const pre=type==="penetration"?"pen":"speed";return[{level:c[pre+"Level"]||0,count:c[pre+"Count"]||0},{level:0,count:0},{level:0,count:0}]}
function openEditor(row){if(!API)return alert("管理者による初期設定が必要です。");const form=$("#formationForm");form.reset();fields();if(row){form.playerName.value=row.playerName||"";form.commonLevel.value=row.characters?.[0]?.level||""}const base=captureDraft(form);formationDrafts=Object.fromEntries(Array.from({length:15},(_,i)=>[i+1,{...base}]));if(row){for(const saved of rowsCache.filter(x=>x.playerName===row.playerName))formationDrafts[+saved.formationNo]=rowToDraft(saved,base)}currentFormationNo=row?+row.formationNo:1;fields();applyDraft(form,formationDrafts[currentFormationNo]);drawFormationTabs();$("#formMessage").textContent="";$("#formDialog").showModal();document.body.style.overflow="hidden"}
let renameTarget="";
function openRename(player){renameTarget=player;const form=$("#renameForm");form.reset();$("#renameCurrent").textContent=player;form.newPlayerName.value=player;$("#renameMessage").textContent="";$("#renameDialog").showModal();document.body.style.overflow="hidden"}
async function renamePlayer(form){if(!renameTarget)return;const f=new FormData(form),body={action:"rename",playerName:renameTarget,newPlayerName:f.get("newPlayerName").trim(),guildPassword:f.get("guildPassword"),editPassword:f.get("editPassword")};$("#renameMessage").textContent="変更中…";try{const r=await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(body)}).then(x=>x.json());if(!r.ok)throw Error(r.error||"名前変更失敗");$("#renameDialog").close();document.body.style.overflow="";renameTarget="";await load()}catch(x){$("#renameMessage").textContent=x.message}}
let resetTarget=null;
function openReset(row){if(!row)return;resetTarget=row;const form=$("#resetForm");form.reset();$("#resetPlayer").textContent=row.playerName;$("#resetNumber").textContent=row.formationNo;$("#resetMessage").textContent="";$("#resetDialog").showModal();document.body.style.overflow="hidden"}
async function resetFormation(form){if(!resetTarget)return;const f=new FormData(form);$("#resetMessage").textContent="初期化中…";const body={action:"delete",playerName:resetTarget.playerName,formationNo:resetTarget.formationNo,guildPassword:f.get("guildPassword"),editPassword:f.get("editPassword")};try{const r=await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(body)}).then(x=>x.json());if(!r.ok)throw Error(r.error||"初期化失敗");$("#resetDialog").close();document.body.style.overflow="";resetTarget=null;await load()}catch(x){$("#resetMessage").textContent=x.message}}
let deletePlayerTarget="";
function openDeletePlayer(player){deletePlayerTarget=player;const form=$("#deletePlayerForm");form.reset();$("#deletePlayerName").textContent=player;$("#deletePlayerMessage").textContent="";$("#deletePlayerDialog").showModal();document.body.style.overflow="hidden"}
async function deletePlayer(form){if(!deletePlayerTarget)return;const f=new FormData(form),body={action:"deletePlayer",playerName:deletePlayerTarget,guildPassword:f.get("guildPassword"),adminPassword:f.get("adminPassword")};$("#deletePlayerMessage").textContent="削除中…";try{const r=await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(body)}).then(x=>x.json());if(!r.ok)throw Error(r.error||"登録者の削除に失敗しました。");$("#deletePlayerDialog").close();document.body.style.overflow="";deletePlayerTarget="";await load()}catch(x){$("#deletePlayerMessage").textContent=x.message}}
$("#openForm").onclick=()=>openEditor(null);$("#closeForm").onclick=()=>{$("#formDialog").close();document.body.style.overflow=""};$("#closeRename").onclick=()=>{$("#renameDialog").close();renameTarget="";document.body.style.overflow=""};$("#renameForm").onsubmit=e=>{e.preventDefault();renamePlayer(e.currentTarget)};$("#closeReset").onclick=()=>{$("#resetDialog").close();resetTarget=null;document.body.style.overflow=""};$("#resetForm").onsubmit=e=>{e.preventDefault();resetFormation(e.currentTarget)};$("#closeDeletePlayer").onclick=()=>{$("#deletePlayerDialog").close();deletePlayerTarget="";document.body.style.overflow=""};$("#deletePlayerForm").onsubmit=e=>{e.preventDefault();deletePlayer(e.currentTarget)};$("#formationForm").onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;formationDrafts[currentFormationNo]=captureDraft(form);$("#formMessage").textContent="保存中…";try{const formations=Object.entries(formationDrafts).filter(([,draft])=>draftHasContent(draft)).map(([no,draft])=>formationPayload(form,+no,draft));if(!formations.length)throw Error("保存する編成を1つ以上入力してください。");const body={action:"saveBatch",playerName:form.playerName.value.trim(),commonLevel:+form.commonLevel.value,guildPassword:form.guildPassword.value,editPassword:form.editPassword.value,formations};const r=await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(body)}).then(x=>x.json());if(!r.ok)throw Error(r.error||"一括保存に失敗しました。");$("#formMessage").textContent=`${r.count||formations.length}編成をまとめて保存しました。`;await load();drawFormationTabs()}catch(x){$("#formMessage").textContent=x.message}};load();
